### PR TITLE
Fix/master/#26 no accept header bug

### LINKED ISSUE #26: Segfault if client doesn't include an accept header
If a client doesn't include an Accept header, look out! The NGINX worker process will segfault and the API client will get a server 500 error. This is caused by the usage of the accept header in the original request on [line 378 of phantom_token.c](https://github.com/curityio/nginx_phantom_token_module/blob/1f62be308c320ec35366101a15fab4ae592dd181/phantom_token.c#L378):

```c
#if(NGX_HTTP_HEADERS)
    module_context->original_accept_header = request->headers_in.accept->value; // Boom!
    ngx_str_set(&introspection_request->headers_in.accept->value, "application/jwt");
#endif
```

The solution is to ensure that `request->headers_in.accept` is not `NULL` before dereferencing that pointer. If the pointer is null, the `module_context->original_accept_header` should be set to `NULL`. Later, when this is used to assign a value to `request->headers_in.accept->value`, use `*/*` instead.

### PR DESCRIPTION
**Pull request by anestos**
When no accept header is present, we set it to `application/jwt` for the introspection to Curity (as previously). The original requests' accept header is not modified, so it is still NULL when the introspection request is handled. In this case, we set it to `*/*` before exiting the module.

This Fixes #26

### CODE REVIEW

File: phantom_token.c [hunk 1]
```diff
@@ -375,21 +395,45 @@ static ngx_int_t handler(ngx_http_request_t *request)
     introspection_request->headers_in.content_length_n = ngx_buf_size(introspection_request_body_buffer);
 
 #if(NGX_HTTP_HEADERS)
-    module_context->original_accept_header = request->headers_in.accept->value;
+    if (request->headers_in.accept == NULL)
```
Comment (travisspencer) [inline phantom_token.c]: looks like what's needed here is a static function that takes a request and an accept header value. with that, you could simply call it twice. that would avoid some duplication

Comment (travisspencer) [reply phantom_token.c]: fixed in 6f379c3dd922d5b57f23e156dd65d73c977a211f.
